### ISSUE TITLE
Support for Extended Grapheme Clusters

### ISSUE THREAD

**Issue by jsbien** [jwilk/unihist2#1]
I would appreciate very much including at least some features of the orphaned https://bitbucket.org/jsbien/unihistext. To make a long story short, it would be nice to count the (extended) graphemic clusters (https://www.unicode.org/glossary/#grapheme_cluster).

**Comment by jwilk** [comment]
Fixed in git:

```console
$ printf '\342\201\212\314\265' | unihist2
1	◌̵	U+0335	COMBINING SHORT STROKE OVERLAY
1	⁊	U+204A	TIRONIAN SIGN ET

$ printf '\342\201\212\314\265' | unihist2 -G
1	⁊̵	U+204A U+0335	TIRONIAN SIGN ET + COMBINING SHORT STROKE OVERLAY
```
